name: Net
layers:
  - type: Linear
    lname: fc1
    in_features: 4
    out_features: 500
  - type: Linear
    lname: fc2
    in_features: 500
    out_features: 500
  - type: Linear
    lname: fc3
    in_features: 500
    out_features: 3
  - type: Softmax
    dim: 1